import React from "react";
import BlogSidebar from "@/components/BlogComponents/BlogSidebar";
import BreadCrumb from "@/components/Common/BreadCrumb";
import PostDetail from "@/components/BlogComponents/PostDetail";
import AuthorCard from "@/components/BlogComponents/AuthorCard";
import RelatedBlog from "@/components/BlogComponents/RelatedBlog";
import Comment from "@/components/BlogComponents/Comment";
import CommentForm from "@/components/BlogComponents/CommentForm";
import VimixLayout from "@/components/Layout/VimixLayout";
import HeaderThree from "@/components/Header/HeaderThree";

export const metadata = {
  title: "Blog Details",
  description: "Generated by create next app",
};

export default function Blog() {
  return (
    <VimixLayout>
      <HeaderThree />
      <BreadCrumb
        pageTitle="Blog Details"
        activePage="Blog Details"
        breadCrumbBg="assets/images/breadcrumb/blog_d.webp"
      />
      <div className="blog-area pt_150 pb_150">
        <div className="container">
          <div className="row row-gap-5">
            <div className="col-lg-8">
              <PostDetail />
              <AuthorCard />
              <RelatedBlog />
              <Comment />
              <CommentForm />
            </div>
            <div className="col-lg-4">
              <BlogSidebar />
            </div>
          </div>
        </div>
      </div>
    </VimixLayout>
  );
}
